[package]
name = "bulletproofs-amcl"
version = "0.1.0"
authors = ["lovesh harchandani <lovesh.bond@gmail.com>"]
edition = "2018"

[dependencies]
rand = "0.5.3"
lazy_static = "1.0"

[dependencies.amcl]
path = "./amcl"

